[project]
repository-type = "library"
versioning-scheme = "semver"
branching-model = "library-release"
release-model = "tagged-release"
primary-language = "python"

[ci]
versions = ["3.12", "3.13", "3.14"]
integration-tests = false

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.1"
